### ISSUE TITLE
colm 0.12.0 tags2.lm test failed

### ISSUE THREAD

**Issue by arm7star** [adrian-thurston/colm#125]
I tested the colm 0.12.0 on linux, but tags2.lm failed.

[root@localhost test]# ../src/colm -d working/tags2.lm
working/tags2.lm:154:5: relative error: <input>:0:2: parse error

"working/tags2.lm:154:5" pointers to "match".
for Switch:tag in S {
        if match Switch
                        ["<lm_switch>" SwitchContent:content "</lm_switch>"]

**Comment by adrian-thurston** [comment]
Hmm, that's a pretty old version. Approx 2014. A lot has changed since then. Are you unable to upgrade for some reason?
